### ISSUE TITLE
emulator key options not listed in documentation

### ISSUE THREAD

**Issue by PeterBBCUser** [scarybeasts/beebjit#12]
F10 Pause emulator (does in Windows anyway, which cause a problem with games like Elite f0 to launch, if you hit it a few times you eventual get to launch)
Alt+F Turbo on off
Alt+T rewind tape
Alt+0 Swap disc drive 0
Alt+1 Swap disc drive 1
Alt+R Restart

**Comment by scarybeasts** [comment]
Thanks for the suggestion! Added KEYS file and references to it.

The Windows F10 thing is a separate bug that I think is fixed on master. I'll do a new Windows build soon-ish.
