### ISSUE TITLE
Is there any way to set the keyboard DIPs in beebjit?

### ISSUE THREAD

**Issue by jamesyoungman** [scarybeasts/beebjit#15]
I would like to achieve the same effect as the B-Em fix in [this Stardot post](https://stardot.org.uk/forums/viewtopic.php?f=4&t=19701&p=274155&hilit=HDFS+DIP#p274155) which makes HDFS work in B-EM, but I can't see any way to set the state of the keyboard DIP switches in beebjit.  I scanned the code, but I'm really not familiar with it.

My rationale here is that I want to use HDFS ROMs in beebjit with HFE disk images to be more confident that geometry guessing isn't a problem (which could be the case in B-EM with SSD images), but for this to work, I need to be able to get HDFS to work in beebjit.

**Comment by scarybeasts** [comment]
New command line flag (value is in hex):
-keyboard-links ff
