### ISSUE TITLE
some ALSA issue stopping beebjit from running

### ISSUE THREAD

**Issue by inversephase** [scarybeasts/beebjit#25]
Just cloned the repo now, and unable to run beebjit. The build succeeds, so I have no idea if the output from build is helpful, but I've included it since running the test is a part of the build and my issue is at the end of it:

$ ./build.sh 
Running built-in unit tests.
unusual:video:horizontal total: 7
unusual:video:vsync pulse width: 16
unusual:video:horizontal total: 1
unusual:video:horizontal total: 3
Running test.rom, JIT, fast.
**BAILING: snd_pcm_hw_params_set_periods failed**

Other applications output sound normally - as examples: firefox, mpv, sdlmame. I suspect the soundcard is being opened with some parameter that it doesn't like (for example my sound device doesn't support the number of buffers or the buffer size you're trying to use). I tried changing the buffer size up top in os_sound_linux.c to 1024 or 512 just to see if it would help; it didn't.

Pulseaudio isn't getting in the way as I haven't got it installed. Since the other applications work I don't think they're blocking the device. I'm not experienced enough with ALSA to work further through the ALSA code. Let me know what you want to try.

**Comment by inversephase** [comment]
Sorry, other pertinent details....
This is an i7 thinkpad, sound device is the built-in HDA Intel sound. I'm using Arch x64. Kernel is 5.6.x. ALSA 1.2.2.

**Comment by scarybeasts** [comment]
Possibly fixed with: https://github.com/scarybeasts/beebjit/commit/be6670d2892463e0dbb8c668aafce59c4c3194c7
