### ISSUE TITLE
Feature Request - Toggle or Colour Surrounding Screen

### ISSUE THREAD

**Issue by ajgbarnes** [scarybeasts/beebjit#31]
It would be a useful feature if it was possible to either switch of the border around the main BBC Micro screen or be able to colour it a different colour.  Helps with grabbing screenshots of just the BBC Micro screen or determining where a pixel is being written (is it on the edge of the screen)?

**Comment by ojwb** [comment]
`-opt video:border-chars=0` should turn off the border.

In MODE7 the cropped area captured is then one character too far left (thanks to correct emulation of 6845 skew I think).

**Comment by scarybeasts** [comment]
I saw this request and thought it would be fun. Image below of what MODE 3 looks like! The implementation isn't really border based, it's based on whether the video chip is rendering display pixels or blank.

Usage e.g. ./beebjit -opt video:background=aa5500

<img width="880" alt="Screenshot 2022-11-29 at 3 21 40 PM" src="https://user-images.githubusercontent.com/26288899/204670644-00ff63e5-9574-4f7f-b2ba-c9d7426d6f46.png">

**Comment by kieranhj** [comment]
On a tangential note, I ended up implementing something similar in the branch kieranhj/debug-border-colour, albeit mapped to an address in the Beeb's memory. I.e. it was emulating a non-existent border colour register to allow raster timings without having to disrupt the main palette. Completely non-authentic but very helpful during the development of timing sensitive code...

**Comment by ojwb** [comment]
@kieranhj Kind of authentic actually - at least there was a real hardware implementation: https://mdfs.net/Info/Comp/BBC/Border/

**Comment by ajgbarnes** [comment]
Thank you @ojwb that looks perfect!
