### ISSUE TITLE
clocksp broken on bbcmic.ro in rocket mode

### ISSUE THREAD

**Issue by BigEd** [scarybeasts/beebjit#33]
Running Richard Russell's [speed.bbc in owlet](https://bbcmic.ro/?experimental=true#%7B%22v%22%3A1%2C%22program%22%3A%2210%20REM%20%3E%20ClockSp%203.00%20%28RTR%29%5Cn15%20TRACE%20OFF%5Cn20%20REM%20Calculate%20CPU%20clock%20speed%5Cn30%20PRINT%5C%22BBC%20BASIC%20CPU%20Timing%20Program%5C%22%5Cn40%20A%25%3D0%3AT%25%3DTIME%3AREPEATA%25%3DA%25%2B1%3AUNTILTIME%3ET%25%2B50%5Cn50%20Z%3D0%3AZ%25%3D0%3AB%3D1.0%3AB%25%3D1%3AF%3D1%2F10%3AC%3D100%3AC%25%3D100%3AD%3D510%3AD%25%3D510%3AF%25%3D3%5Cn60%20REPEAT%3AC%3DC*10%3AC%25%3DC%25*10%3AD%3DD*10%3AD%25%3DD%25*10%3AF%25%3DF%25*10%3AF%3DF*10%3AA%25%3DA%25DIV10%3AUNTILA%25%3C50%5Cn65%20Z%3DZ%2B0.5%3AC%3DC%2B0.5%3AD%3DD%2B0.5%5Cn70%20PRINT%5C%22Really%20real%20REPEAT%20loop%20%5C%22%3B%3AT%25%3DTIME%3AA%3DZ%3AREPEATA%3DA%2BB%3AUNTILA%3EC%3AT%25%3DTIME-T%25%3APROCp%28F*41000%2FT%25%29%5Cn80%20PRINT%5C%22Integer%20REPEAT%20loop%20%20%20%20%20%5C%22%3B%3AT%25%3DTIME%3AA%25%3DZ%25%3AREPEATA%25%3DA%25%2BB%25%3AUNTILA%25%3EC%25%3AT%25%3DTIME-T%25%3APROCp%28F*23900%2FT%25%29%5Cn90%20PRINT%5C%22Really%20real%20FOR%20loop%20%20%20%20%5C%22%3B%3AT%25%3DTIME%3AFORA%3DZ%20TO%20D%20STEP%20B%3ANEXT%3AT%25%3DTIME-T%25%3APROCp%28F*51200%2FT%25%29%5Cn100%20PRINT%5C%22Integer%20FOR%20loop%20%20%20%20%20%20%20%20%5C%22%3B%3AT%25%3DTIME%3AFORA%25%3DZ%25%20TO%20D%25%20STEP%20B%25%3ANEXT%3AT%25%3DTIME-T%25%3APROCp%28F*17800%2FT%25%29%5Cn110%20PRINT%5C%22Trig%2FLog%20test%20%20%20%20%20%20%20%20%20%20%20%5C%22%3B%3AIFCOS0%3D0%3APRINTSPC4%5C%22%3Cnone%3E%5C%22%5Cn120%20IFCOS0%3C%3E0%3AA%3D1%3AT%25%3DTIME%3AFORJ%25%3D1%20TO%20F%25%3AA%3DTAN%28ATN%28EXP%28LN%28SQR%28A*A%29%29%29%29%29%2B1%3ANEXT%3AT%25%3DTIME-T%25%3APROCp%28F*68800%2FT%25%29%5Cn130%20REM%20PRINT%5C%22Ackermann%20Recursion%20%5C%22%3B%5Cn140%20REM%20M%25%3D3%3AT%25%3DTIME%3AFORN%25%3D1%20TO%203%3AZ%25%3DFNAck%28M%25%2CN%25%29%3ANEXT%3AT%25%3DTIME-T%25%3APROCp%28F*255400%2FT%25%29%5Cn150%20PRINT%5C%22String%20manipulation%20%20%20%20%20%5C%22%3B%5Cn160%20T%25%3DTIME%3AA%24%3D%5C%22STRINGMANIPULATIONTEST%5C%22%3AFORA%25%3D0TOF%25*4%3AA%24%3DRIGHT%24%28MID%24%28A%24%2CLENA%24%2F2%2CLENA%24%2F4%2B1%29%2BRIGHT%24%28A%24%2CLENA%24%2F4%29%2BMID%24%28A%24%2CLENA%24%2F2%2C2%29%2BLEFT%24%28A%24%2CLENA%24%2F4%29%2BMID%24%28A%24%2CLENA%24%2F4%2CLENA%24%2F4%2B1%29%2CLENA%24%29%3ANEXT%3AT%25%3DTIME-T%25%3APROCp%28F*72750%2FT%25%29%5Cn170%20PRINT%5C%22Procedure%20call%20%20%20%20%20%20%20%20%20%20%5C%22%3B%3AT%25%3DTIME%3AFORA%25%3DZ%25%20TO%20D%25%3APROCtest%3ANEXT%3AT%25%3DTIME-T%25%3APROCp%28F*80500%2FT%25%29%5Cn180%20PRINT%5C%22GOSUB%20call%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5C%22%3B%3AT%25%3DTIME%3AFORA%25%3DZ%25%20TO%20D%25%3AGOSUB300%3ANEXT%3AT%25%3DTIME-T%25%3APROCp%28F*90000%2FT%25%29%5Cn190%20PRINT%5C%22Combined%20Average%20%20%20%20%20%20%20%20%5C%22%3B%3APROCp%28FNspeed%29%5Cn200%20PRINT'%5C%22Compared%20with%20a%202.00MHz%20BBC%20B%5C%22%5Cn210%20END%5Cn220%20%3A%5Cn230%20DEFFNAck%28M%25%2CN%25%29%5Cn240%20IF%20M%25%3D0%3A%3DN%25%2B1%5Cn250%20IF%20N%25%3D0%3A%3DFNAck%28M%25-1%2C1%29%5Cn260%20%3DFNAck%28M%25-1%2CFNAck%28M%25%2CN%25-1%29%29%5Cn270%20%3A%5Cn280%20DEFPROCtest%3AENDPROC%5Cn290%20%3A%5Cn300%20RETURN%5Cn310%20%3A%5Cn320%20DEFPROCp%28T%25%29%3APRINTRIGHT%24%28%5C%22%20%20%20%20%20%5C%22%2BSTR%24%28T%25DIV100%29%2C6%29%3B%5C%22.%5C%22%3BRIGHT%24%28%5C%220%5C%22%2BSTR%24%28T%25%29%2C2%29%3B%5C%22MHz%5C%22%3BCHR%248%3AENDPROC%5Cn330%20%3A%5Cn340%20REM%20This%20is%20calibrated%20against%20a%5Cn350%20REM%20BBC%20model%20B%20with%20no%20second%5Cn360%20REM%20processor%2C%20running%20BASIC%20II%5Cn370%20REM%20and%20with%20almost%20all%20interupts%5Cn380%20REM%20turned%20off%20using%3A%5Cn390%20REM%20%3F%26FE4E%3D%263F%5Cn400%20REM%20This%20gives%202.00MHz.%5Cn410%20%3A%5Cn420%20REM%20Savage%20Floating%20Point%20test%20and%5Cn430%20REM%20Ackermann%20Recursion%20test%20added%5Cn440%20REM%20-Mar-1993%2C%20based%20on%20A%26B%20Jan%2090.%5Cn450%20%3A%5Cn460%20REM%20Version%202.00%20recalibrates%5Cn470%20REM%20itself%20for%20faster%20systems%5Cn480%20REM%2015-Mar-2002%5Cn490%20%3A%5Cn500%20DEFFNspeed%3ALOCAL%20A%2CB%2CC%2CD%2CF%2CZ%2CA%25%2CB%25%2CC%25%2CD%25%2CF%25%2CQ%25%2CR%25%2CS%25%2CU%25%2CV%25%2CW%25%2CX%25%2CY%25%2CZ%25%5Cn510%20A%25%3D0%3AT%25%3DTIME%3AREPEATA%25%3DA%25%2B1%3AUNTILTIME%3ET%25%2B50%5Cn520%20Z%3D0%3AZ%25%3D0%3AB%3D1.0%3AB%25%3D1%3AF%3D1%2F10%3AC%3D100%3AC%25%3D100%3AD%3D510%3AD%25%3D510%3AF%25%3D3%5Cn530%20REPEAT%3AC%3DC*10%3AC%25%3DC%25*10%3AD%3DD*10%3AD%25%3DD%25*10%3AF%25%3DF%25*10%3AF%3DF*10%3AA%25%3DA%25DIV10%3AUNTILA%25%3C50%5Cn525%20Z%3DZ%2B0.5%3AC%3DC%2B0.5%3AD%3DD%2B0.5%5Cn540%20T%25%3DTIME%3AA%3DZ%3AREPEATA%3DA%2BB%3AUNTILA%3EC%3AT%25%3DTIME-T%25%3AU%25%3DF*41000%2FT%25%5Cn550%20T%25%3DTIME%3AA%25%3DZ%25%3AREPEATA%25%3DA%25%2BB%25%3AUNTILA%25%3EC%25%3AT%25%3DTIME-T%25%3AV%25%3DF*23900%2FT%25%5Cn560%20T%25%3DTIME%3AFORA%3DZ%20TO%20D%20STEPB%3ANEXT%3AT%25%3DTIME-T%25%3AW%25%3DF*51200%2FT%25%5Cn570%20T%25%3DTIME%3AFORA%25%3DZ%25%20TO%20D%25%20STEPB%25%3ANEXT%3AT%25%3DTIME-T%25%3AX%25%3DF*17800%2FT%25%5Cn580%20Y%25%3DX%25%3AIFCOS0%3C%3E0%3AA%3D1%3AT%25%3DTIME%3AFORJ%25%3D1%20TO%20F%25%3AA%3DTAN%28ATN%28EXP%28LN%28SQR%28A*A%29%29%29%29%29%2B1%3ANEXT%3AT%25%3DTIME-T%25%3AY%25%3DF*68800%2FT%25%5Cn590%20T%25%3DTIME%3AA%24%3D%5C%22STRINGMANIPULATIONTEST%5C%22%3AFORA%25%3D0TOF%25*4%3AA%24%3DRIGHT%24%28MID%24%28A%24%2CLENA%24%2F2%2CLENA%24%2F4%2B1%29%2BRIGHT%24%28A%24%2CLENA%24%2F4%29%2BMID%24%28A%24%2CLENA%24%2F2%2C2%29%2BLEFT%24%28A%24%2CLENA%24%2F4%29%2BMID%24%28A%24%2CLENA%24%2F4%2CLENA%24%2F4%2B1%29%2CLENA%24%29%3ANEXT%3AT%25%3DTIME-T%25%3AS%25%3DF*72750%2FT%25%5Cn600%20T%25%3DTIME%3AFORA%25%3DZ%25%20TO%20D%25%3APROCtest%3ANEXT%3AT%25%3DTIME-T%25%3AR%25%3DF*80500%2FT%25%5Cn610%20T%25%3DTIME%3AFORA%25%3DZ%25%20TO%20D%25%3AGOSUB300%3ANEXT%3AT%25%3DTIME-T%25%3AQ%25%3DF*90000%2FT%25%5Cn620%20%3DINT%28%28Q%25%2BR%25%2BS%25%2BU%25%2BV%25%2BW%25%2BX%25%2BY%25%29%2F%2878%2F10%29%29%5Cn630%20REM%20Returns%20CPU%20speed*100%5Cn%5Cn%22%7D), it's fine, but in rocket mode it restarts the machine and then gets stuck.

**Comment by scarybeasts** [comment]
I think this is an owlet issue (with the rocket sync) and not a beebjit issue. owlet might even be fixed now.
