### ISSUE TITLE
Sounds on Depeche mode demo is broken

### ISSUE THREAD

**Issue by mattgodbolt** [scarybeasts/beebjit#36]
With this disc: https://bitshifters.github.io/content/tyb-enjoy.ssd it sounds mostly like noise. I ran it with:

```
./beebjit -disc ~/dev/personal/jsbeeb/discs/sound.ssd
```

with and without `-mode interp`.

**Comment by scarybeasts** [comment]
It's designed to run on a master, so pass the -master flag and it's fine.
It also runs in model B mode if you load up a bunch of swram banks, e.g. -swram 4 -swram 5 -swram 6 -swram 7 (jsbeeb is configured with a ton of model B swram if I remember correctly.)
