### ISSUE TITLE
LinearTTX test issue

### ISSUE THREAD

**Issue by hoglet67** [scarybeasts/beebjit#37]
HI Chris,

I've just been running throught your set of display tests (on a real Master and on BeebFPGA)

I can't get the LinearTTX to work.

On a real Master it hangs after a couple of seconds:
![capture5](https://user-images.githubusercontent.com/1951463/168324423-fd1efe04-808d-4a1a-82e4-c79f2587b758.png)

On BeebFPGA it reboots at about the same point.

I've got all four banks of SWRAM available.

Any ideas?

Dave

**Comment by scarybeasts** [comment]
Hi Dave, do you happen to know what type of CRTC is in the real Master? Many Masters have a VLi 6845 which isn't compatible with the Hitachi 6845. Other Masters have a Toshiba 6845, which appears to behave the same as a Hitachi 6845.

**Comment by scarybeasts** [comment]
I'll also note that in beebjit, the test case appears to be bistable. Specifically, the main Kefrens effect might either render correctly, or render mostly off-screen to the right side. I don't know if that mirrors a Master or not.

**Comment by hoglet67** [comment]
It's a Hitachi HD6845S

**Comment by hoglet67** [comment]
Do you have a real Model B or Master you could try it on?

**Comment by scarybeasts** [comment]
The test case is BBC Master only. I don't have a real Master.
The test case was sent to me by a Bitshifter who I believe developed it on a real Master. Let me check.

**Comment by hoglet67** [comment]
When it hangs it seems to be polling &FE28, which is the 1770.
```
13.861182 : Mem Rd Watch hit at 1DC9 reading FE28:81  .
13.861210 : Mem Rd Watch hit at 1DC9 reading FE28:40  @
13.861210 : Mem Rd Watch hit at 1DC9 reading FE28:81  .
13.861238 : Mem Rd Watch hit at 1DC9 reading FE28:00  .
13.861238 : Mem Rd Watch hit at 1DC9 reading FE28:81  .
13.861266 : Mem Rd Watch hit at 1DC9 reading FE28:00  .
13.861266 : Mem Rd Watch hit at 1DC9 reading FE28:81  .
Interrupted
03.748336 : 1DCB : 29 01    : AND #$01
>> 
```
I'm guessing this means it must include it's own disk access code, so won't work with MMFS.

Let me try to find a floppy....

**Comment by hoglet67** [comment]
OK, it works fine from floppy....

Very strange that it includes it's own 1770 disk access code....

**Comment by scarybeasts** [comment]
Ah yes! Sorry about that. The interesting LinearTTX test case is wrapped inside an experimental demo framework. This framework includes "quicdisc", a custom floppy driver that frees up RAM and removes dependencies on DFS / MOS etc.

**Comment by VectorEyes** [comment]
Yes, sorry, this is a great example of a test case that doesn't only test one thing! It should be possible to create a version that doesn't rely on quicdisc.

**Comment by hoglet67** [comment]
> It should be possible to create a version that doesn't rely on quicdisc.

It would be worth doing that I think, if this test case is covers things that other ones don't

I'm working thorugh everything I can find at the moment:
https://github.com/hoglet67/BeebFpga/blob/dev/test/NOTES.txt

The only other one that's causing me problems is the "rvi-working.ssd" which works fine on the real master, but  is seriously garbled up on BeebFPGA. That's my task for the weekend....
