### ISSUE TITLE
Mac version sometimes fails to start

### ISSUE THREAD

**Issue by TobyLobster** [scarybeasts/beebjit#39]
Sometimes beebjit (Mac tagged version v0.9.7) fails to start, but trying again often works. Here is the output where I tried to run it once and it failed, but trying again then worked:

```
% ./beebjit -0 test/games/Disc108-FroggerRSCB.ssd
BAILING: mmap in wrong location (expected 0x1f000000, got 0x20000000), heap 0x511a30 binary 0x407880
% ./beebjit -0 test/games/Disc108-FroggerRSCB.ssd
info:audio:sub-period size 86 time 1791us
unimplemented:misc:write of TUBE region

```

**Comment by scarybeasts** [comment]
Thanks for the report. It should be possible to tweak a few constants to get this to work... hopefully!

Out of curiosity, what version of macOS is this?

**Comment by TobyLobster** [comment]
Thanks - I'm on macOS Big Sur.

**Comment by scarybeasts** [comment]
Does it work reliably if you edit asm/asm_platform.h and change:

#define K_BBC_MEM_RAW_ADDR                 0x1f008000

to

#define K_BBC_MEM_RAW_ADDR                 0x27008000

?

**Comment by TobyLobster** [comment]
[Archive.zip](https://github.com/scarybeasts/beebjit/files/8811923/Archive.zip)
Like this?

**Comment by scarybeasts** [comment]
Thanks, that's perfect. It looks like this older version of macOS likes to reserve huge malloc areas, and these are conflicting with beebjit's attempts to reserve address space for various things.

Can you try the latest code on master (as of commit: https://github.com/scarybeasts/beebjit/commit/f3160a3b5a48ae254fb8e4adcb0d8d214457ef33) and see if it works now? It's an attempt at fixing this in a simple manner, which might not be perfect, but might do the trick. It squishes beebjit's mappings together so that the huge malloc areas will be placed elsewhere.

**Comment by scarybeasts** [comment]
[For posterity, here's the older version of macOS grabbing 0x30000000 before beebjit can get it!!]

mapped file                  2a008000-2a010000     [   32K     0K     0K     0K] rw-/rwx SM=S/A          /private/tmp/beebjit6q9lU1
mapped file                  2b008000-2b010000     [   32K     0K     0K     0K] rw-/rwx SM=S/A          /private/tmp/beebjit6q9lU1
VM_ALLOCATE (reserved)       2b010000-2b018000     [   32K     0K     0K     0K] rw-/rwx SM=NUL          reserved VM address space (unallocated)
MALLOC_MEDIUM                30000000-30800000     [ 8192K  1624K  1624K     0K] rw-/rwx SM=PRV          DefaultMallocZone_0x4cf000
MALLOC_MEDIUM (reserved)     30800000-38000000     [120.0M     0K     0K     0K] rw-/rwx SM=NUL          DefaultMallocZone_0x4cf000

**Comment by TobyLobster** [comment]
That is working nicely - thank you, thank you! I've tried launching 15 times and it succeeded each time.

**Comment by scarybeasts** [comment]
Great. Thanks for helping sort out the teething troubles with the new macOS port!
