### ISSUE TITLE
MODE 7 with 6845 skew vs -opt video:border-chars=0

### ISSUE THREAD

**Issue by ojwb** [scarybeasts/beebjit#45]
`-opt video:border-chars=0` captures a MODE 7 screen offset one character cell to the right (so the right-hand column is chopped off and there's an extra blank column on the left).  This changed when 6845 skew was implemented in b08d591b1b34cb963ddd6dcaa286e5c97f5bd38f.

The new behaviour is probably more true to real hardware, but not helpful if you're trying to capture screenshots or video.  I ran into this with BBCMicroBot - I think the live bot must be using an old build of beebjit currently, but this is essentially a blocker for upgrading to a newer beebjit version.

I think it would make sense for `video:border-chars` to adjust the captured area for this offset.  I can probably attempt a patch if that's helpful and this would be an acceptable solution.

**Comment by scarybeasts** [comment]
Thanks, interesting! The video:border-chars facility doesn't really know about modes and I think it's better that way (it only knows about window position relative to the virtual CRT horizontal sync).

I could look at adding a switch to "fix" the position of MODE 7. Maybe patching the ROM's hsync value...

**Comment by scarybeasts** [comment]
Ok, here's a good way to fix it for the bot. The debug "writem" command is capable of patching ROM, so:
(Uses the new video:background option as a visual aid for centering.)

./beebjit -opt video:background=aa5500 -commands 'writem c4a0 0x34;c;'

It works with the model B ROM (v1.2) to patch a table of MODE 7 parameters for the 6845 video chip, and move horizontal sync a bit later --> screen shifts left to the same place as the other modes.

**Comment by ojwb** [comment]
FWIW I wasn't suggesting `video:border-chars` would need to know about screen modes as such - it only needs to know if the skew is happening, so probably something like checking bit 1 of the video control register (which is set to 1 if the teletext chip is in use) would work.

Modifying the ROM inside the emulation doesn't seem a nice approach as it can change the output of programs sent to the bot compared to running them in another emulator (I know without checking it'll change the output of at least one of my previous ones!)  For example. reading the ROMs is a fast source of (admittedly poor quality) pseudo-random numbers which can be read in very little BASIC code.

We can patch our beebjit build to address this for the bot though.

**Comment by scarybeasts** [comment]
Point taken. How about an option to restore older beebjit behavior (i.e. push MODE 7 back to left)?

**Comment by ojwb** [comment]
That'd be great.

**Comment by scarybeasts** [comment]
Hopefully adequately fixed in:
https://github.com/scarybeasts/beebjit/commit/e6ea6a044c7e03d79102bb051afc1d2a8741cce0
-opt video:hack-legacy-shift-mode7

**Comment by ojwb** [comment]
Thanks- I can confirm this addresses the issue in a manual test.

I'm struggling to get the bot's testsuite to pass using this, but I think that's a separate issue I've been trying to pin down.  I'll open a new ticket once I can give a coherent description of it.
