### ISSUE TITLE
MakeUEF 2.4 8e1 8o1 Parity

### ISSUE THREAD

**Issue by PeterBBCUser** [scarybeasts/beebjit#50]
makeUEF 2.4 is out it fixes the swapping parity bug only problem is emulators are written to fix the bug in software, beebjit & mame now will not load tape files that are created with makeUEF that use 8e1 8o1 parity now are broken in the emulator (beebem & B-em do not care as they do not look at the parity chunk, they ignores it), and guess it will also break PlayUEF.
I have made new UEF's (with MakeUEF 2.4) of all the known titles I have come across that use 8e1 8o1 parity on a google drive. https://drive.google.com/drive/folders/1FXKW4NOKuOC4yf6-W8IoqtxIkrxC2PpL?usp=share_link

**Comment by scarybeasts** [comment]
Thanks for the report!

It looks like MakeUEF 2.4 files have the same minor version in the header as 2.3 (which appears to be 0x0A). So I'm detecting file version by looking at the text in the origin chunks.

Seems to be working; I'll commit the patch shortly.

Is it ok if I add one of your test files to the beebjit test/tapes directory?

**Comment by PeterBBCUser** [comment]
sure be by guest.
